project:
  type: book
  output-dir: docs


book:
  title: "Zadania ze statystyki"
  author: "Wojciech Bonna"
  date: today
  date-format: "DD-MM-YYYY"
  chapters:
    - index.qmd
    - statystyka_sobczyk.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab
    
    code-fold: true
    code-line-numbers: true
    
  pdf:
    documentclass: scrreprt



