project:
  type: book
  output-dir: docs


book:
  title: "Zadania ze statystyki"
  author: "Wojciech Bonna"
  date: today
  date-format: "DD-MM-YYYY"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



