# Statystyka - Mieczysław Sobczyk

## Opisowa analiza struktury zjawisk masowych

1.  W dwóch komórkach organizacyjnych przedsiębiorstwa pracują po dwie osoby. W pierwszej komórce miesięczne zarobki brutto wynoszą odpowiednio 1400 zł i 1600 zł, a w komórce drugiej - 2000 zł i 4000 zł. Związki zawodowe domagają się zwiększenia średniego zarobku w obydwu komórkach. Jak to zrobić, nie zwalniając pracowników i nie wydając na podwyżki ani grosza?

<!-- -->

    Przesunąć pracownika zarabiającego 2000 zł z komórki II do I.

2.  W mieszance jest 20 kg składnika *A* w cenie 15 zł za kilogram, 25 kg składnika *B* w cenie 20 zł za kilogram oraz 5 kg składnika *C* w cenie 30 zł za kilogram. Oblicz cenę jednego kilograma mieszanki.

```{r}
wagi <- c(20, 25, 5)
ceny <- c(15, 20, 30)

x <- sum(wagi*ceny) / sum(wagi)

cat(x, "zł")
```

3.  Jaka jest średnia arytmetyczna dwóch liczb, jeżeli:

    a\) pierwsza liczba jest o 5 większa od drugiej;

    b\) suma 10% pierwszej liczby i połowy drugiej liczby jest równa 4?

```{=tex}
\begin{equation}
  \left\{
  \begin{array}{l}
    x_{1} = x_{2} + 5\\
    \frac{x_{1}}{10} + \frac{x_{2}}{2} = 4
  \end{array}
  \right.
\end{equation}
```
```{=tex}
\begin{equation}
  \begin{array}{l}
    \frac{x_{2} + 5}{10} + \frac{x_{2}}{2} = 4 | \cdot10 \\
    x_{2} + 5 + 5x_{2} = 40 \\
    6x_{2} = 35 \\
    x_{2} = \frac{35}{6} \\
    x_{1} = \frac{35}{6} + 5 = \frac{65}{6} \\
    \bar{x} = \frac{x_{1} + x_{2}}{2} = \frac{\frac{65}{6} + \frac{35}{6}}{2} = \frac{100}{12} = 8\frac{1}{3}
  \end{array}
\end{equation}
```
4.  Średnia arytmetyczna trzech kolejnych liczb naturalnych wynosi 8. Znajdź te liczby.
5.  Ojciec Huberta jest teraz 3 razy starszy od syna. Za 10 lat ojciec będzie dwa razy starszy od syna. Jaki jest obecnie przeciętny wiek tych osób?
6.  W pewnym zakładzie zbadano pracowników bezpośrednio produkcyjnych pod względem stażu pracy. Okazało się, że 25% tych pracowników pracowało krócej niż 6 lat, połowa od 6 do 12 lat, natomiast najdłuższy staż pracy pozostałych pracowników był równy 18 lat. Średni czas pracy pracowników administracyjno-biurowych w tym zakładzie wynosił 12 lat. Jaki jest średni staż pracy ogółu pracowników tego zakładu, jeśli grupa pracowników bezpośrednio produkcyjnych jest 2,5-krotnie liczniejsza od administracyjno-biurowych?
7.  Obwód trójkąta jest równy 21 cm. Pierwszy bok jest równy średniej arytmetycznej pozostałych boków. Drugi bok stanowi 75% boku trzeciego. Oblicz długości boków trójkąta.
8.  Średni miesięczny zarobek 25 pracowników w pewnej spółce akcyjnej wynosił 2000 zł, gdyż 20 osób zarabiało 1400 zł, 4 osoby po 3000 zł, a 1 osoba 10000 zł. Dwudziestu najniżej zarabiających pracowników zażądało podniesienia ich płac do poziomu średniej płacy w spółce. Żądanie zostało spełnione. Czy po podwyżce zarabiają oni powyżej średniej?
9.  Stosunek dwóch liczb całkowitych wynosi 3:5. Jeżeli pierwszą liczbę zmniejszymy o 2, to otrzymamy 40% drugiej liczby. Jaka jest średnia arytmetyczna tych liczb?
10. W pewnej grupie uczniów średnia wieku wynosi 11 lat. Najstarszy z nich ma 17 lat, a średnia wieku pozostałych wynosi 10 lat. Ile uczniów liczy ta grupa?
11. Iloczyn dwóch kolejnych liczb parzystych jest o 296 mniejszy od iloczynu następnych dwóch liczb parzystych. Oblicz średnią arytmetyczną tych czterech liczb.
12. Z miast *A* i *B* odległych o 35 km wyjeżdżają dwaj rowerzyści. Prędkość jazdy jednego z nich jest równa 75% prędkości drugiego. Oblicz prędkość każdego z nich, wiedząc, że spotkają się po 1,25h jazdy.
